---
language: ruby
script: "SPEC_OPTS='--color --format documentation' bundle exec rake spec"
notifications:
  email: false
rvm:
  - 1.9.3
  - 1.8.7
  - 2.0.0
env:
  - PUPPET_VERSION='~> 3.4.0'
  - PUPPET_VERSION='~> 2.7.0'
